### ISSUE TITLE
Error while running the training script

### ISSUE THREAD

**Issue by kingafy** [UKPLab/gpl#4]
2022-04-14 06:00:25] INFO [gpl.toolkit.pl.run:60] Begin pseudo labeling
0%| | 0/140000 [00:00<?, ?it/s]
Traceback (most recent call last):
File "/home/ec2-user/SageMaker/gpl/gpl/toolkit/pl.py", line 63, in run
batch = next(hard_negative_iterator)
File "/home/ec2-user/SageMaker/kernels/gpl_env/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 530, in __next__
data = self._next_data()
File "/home/ec2-user/SageMaker/kernels/gpl_env/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 569, in _next_data
index = self._next_index() # may raise StopIteration
File "/home/ec2-user/SageMaker/kernels/gpl_env/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 521, in _next_index
return next(self._sampler_iter) # may raise StopIteration
StopIteration

**Comment by kwang2049** [comment]
Hi @kingafy, could you please try running this sample script: https://github.com/UKPLab/gpl/blob/main/sample-data/sample-data.sh and tell me whether you still have the error?

**Comment by kwang2049** [comment]
I found this error might be due to corpus size < `batch_size_gpl`. Could you please check whether this is the case? I will also add this assertion in the new version of the code.

**Comment by kwang2049** [comment]
Feel free to open it again if you still encounter such an issue.
